import { ThemeCopy } from "./types";

export const awsTheme: ThemeCopy = {
  id: "aws",
  providerName: "Amazon Web Services",
  providerShort: "AWS",
  consoleName: "AWS Management Console",
  domain: "console.aws.amazon.com",
  regionLabel: "ap-south-1",
  regionCity: "Mumbai",
  accountLabel: "Account ID",
  accountId: "4829-1033-7122",
  userArn: "arn:aws:iam::482910337122:user/harsh-goilkar",
  searchPlaceholder: "Search for services, features, resignation letters...",
  bootSequence: [
    "Establishing secure session over TLS 1.3 ...",
    "Validating SSO credentials for harsh-goilkar ...",
    "Assuming role arn:aws:iam::482910337122:role/HarshGoilkar-FullAccess ...",
    "Checking MFA token ... accepted",
    "Resolving region: ap-south-1 (Mumbai) ...",
    "Loading service catalog (200+ services, you'll use 12) ...",
    "Scanning for idle EC2 instances left running since 2024 ... 0 found (unlike production)",
    "Calculating estimated monthly charges: ₹0.00 (this time) ...",
    "Provisioning console shell ...",
    "Rendering sidebar, breadcrumbs, and mild anxiety ...",
    "Console ready.",
  ],
  toastBank: [
    "Cost anomaly detected: ₹0.00 → ₹0.00. Still within budget.",
    "New IAM policy attached: CanBrag:ReadOnly",
    "CloudTrail logged this visit. Everything is logged. Always.",
    "Auto-scaling event: recruiter interest +1. Consider provisioning an offer letter.",
    "Reminder: this portfolio has 100% uptime, unlike some EC2 instances we don't talk about.",
    "Cost-benefit analysis complete: hiring this candidate is cheaper than another failed POC.",
    "Health check passed on first attempt. Rare. Worth a follow-up email.",
    "Auto-remediation available: replace your current hiring pipeline with this one page.",
  ],
  vendorCardTitle: "Amazon Web Services",
  vendorCardSubtitle: "The industry standard. 200+ services. 12 you'll actually use.",
  vendorCardJokes: [
    "IAM policies precise enough to need a law degree and a therapist on retainer.",
    "47 ways to store a file. Zero are the one you actually wanted.",
    "A free tier that expires the exact week you finally understand the product.",
    "Support answers pulled from the same docs page you already had open.",
    "A pricing calculator that requires its own separate pricing calculator.",
    "Documented in 12 places. Correct in 1. Currently unknown which.",
  ],
  vendorCardCta: "Launch Console",
  roastVerdict: "The industry default. Chosen the way most defaults are: by not choosing.",
  roastStats: [
    { label: "Pricing calculator clarity", value: 6, display: "6%" },
    { label: "IAM policy readability", value: 9, display: "9%" },
    { label: "Surprise-bill probability", value: 94, display: "94%" },
    { label: "Console load time you've made peace with", value: 100, display: "100%" },
  ],
  notFoundTitle: "ResourceNotFoundException",
  notFoundCode: "404",
  notFoundBody:
    "The resource you requested does not exist, was deprecated without a changelog entry, or was deleted by someone who swore they were in the dev account.",
  notFoundCta: "Return to Console Home",
  navItems: [
    { key: "home", label: "Console Home", href: "/console/home", icon: "home" },
    { key: "iam", label: "IAM", href: "/console/iam", icon: "iam" },
    { key: "compute", label: "EC2", href: "/console/compute", icon: "compute" },
    { key: "storage", label: "S3", href: "/console/storage", icon: "storage" },
    { key: "catalog", label: "Service Catalog", href: "/console/catalog", icon: "catalog" },
    { key: "monitoring", label: "CloudWatch", href: "/console/monitoring", icon: "monitoring" },
    { key: "billing", label: "Billing & Support", href: "/console/billing", icon: "billing" },
  ],
  billingNote: "Estimated month-to-date charges: ₹0.00. Free Tier eligible until the recruiter reads this.",
  footerNote: "© 2026 Harsh Goilkar. Not an actual Amazon Web Services property. Please don't sue, Andy.",
  logoLetter: "aws",
};
