import { ThemeCopy } from "./types";

export const gcpTheme: ThemeCopy = {
  id: "gcp",
  providerName: "Google Cloud Platform",
  providerShort: "Google Cloud",
  consoleName: "Google Cloud Console",
  domain: "console.cloud.google.com",
  regionLabel: "asia-south1",
  regionCity: "Mumbai",
  accountLabel: "Project ID",
  accountId: "harsh-goilkar-portfolio-hq7x2",
  userArn: "harshgoilkar27@gmail.com",
  searchPlaceholder: "Search products, resources, deprecated APIs...",
  bootSequence: [
    "Authenticating with Google Identity Platform ...",
    "Verifying 2-Step Verification ... approved",
    "Switching active project: harsh-goilkar-portfolio-hq7x2 ...",
    "Enabling required APIs (this may take a few minutes, or fiscal quarters) ...",
    "Resolving region: asia-south1 (Mumbai) ...",
    "Checking for services scheduled to be deprecated this week ... 3 found",
    "Estimating monthly cost: $0.00 (free trial credits intact) ...",
    "Provisioning Cloud Shell ... please hold",
    "Loading Cloud Console shell ...",
    "Rendering sidebar with entirely too many shades of blue ...",
    "Console ready.",
  ],
  toastBank: [
    "Billing alert: $0.00 spent of $300 free trial credit.",
    "IAM binding added: roles/canBrag.viewer",
    "Cloud Logging captured this page view. Transparently, and forever.",
    "Uptime check passed: this portfolio has never been sunset.",
    "Reminder: unlike some Google products, this one is not getting killed next year.",
    "Autoscaler note: recruiter engagement trending up and to the right. Consider scaling up the offer.",
    "Cost-benefit analysis complete: hiring this candidate is cheaper than another canceled product.",
    "Deprecation notice: your current shortlist, effective as soon as you finish reading this.",
  ],
  vendorCardTitle: "Google Cloud Platform",
  vendorCardSubtitle: "Best-in-class Kubernetes. Occasionally best-in-class attention span.",
  vendorCardJokes: [
    "A beautifully designed console for a product line they'll sunset next Tuesday.",
    "IAM so simple you'll accidentally grant yourself Owner on the whole org.",
    "World-class Kubernetes, invented here, then slowly orphaned by its own creator.",
    "Free trial credits that expire the exact week your side project gets traction.",
    "Support chat staffed by a very polite, occasionally confident chatbot.",
    "A killed-by-Google graveyard with better UX than most companies' live products.",
  ],
  vendorCardCta: "Launch Console",
  roastVerdict: "The tasteful choice. Great engineering, questionable commitment issues.",
  roastStats: [
    { label: "Product longevity confidence", value: 23, display: "23%" },
    { label: "IAM permission model simplicity", value: 97, display: "97% (too simple)" },
    { label: "Chance this gets deprecated", value: 61, display: "61%" },
    { label: "Kubernetes bragging rights", value: 100, display: "100%" },
  ],
  notFoundTitle: "This page has been sunset",
  notFoundCode: "404",
  notFoundBody:
    "The page you're looking for was deprecated, merged into a product with a worse name, or quietly removed in a blog post nobody read.",
  notFoundCta: "Return to Dashboard",
  navItems: [
    { key: "home", label: "Dashboard", href: "/console/home", icon: "home" },
    { key: "iam", label: "IAM & Admin", href: "/console/iam", icon: "iam" },
    { key: "compute", label: "Compute Engine", href: "/console/compute", icon: "compute" },
    { key: "storage", label: "Cloud Storage", href: "/console/storage", icon: "storage" },
    { key: "catalog", label: "Marketplace", href: "/console/catalog", icon: "catalog" },
    { key: "monitoring", label: "Cloud Monitoring", href: "/console/monitoring", icon: "monitoring" },
    { key: "billing", label: "Billing & Support", href: "/console/billing", icon: "billing" },
  ],
  billingNote: "Month-to-date spend: $0.00 of $300 free trial. Auto-upgrade to paid: declined, wisely.",
  footerNote: "© 2026 Harsh Goilkar. Not an actual Google Cloud property. Please don't sunset me, Sundar.",
  logoLetter: "G",
};
