"use client";

import { useTheme } from "@/lib/theme-context";
import { education, person } from "@/lib/content";
import { PageHeader } from "@/components/ui/page-header";
import { Panel, PanelHeader } from "@/components/ui/panel";
import { Badge, Chip } from "@/components/ui/badge";
import { PolicyDocument } from "@/components/ui/policy-json";
import { ShieldCheck, KeyRound, Users } from "lucide-react";

export default function IamPage() {
  const { theme } = useTheme();
  const isAws = theme.id === "aws";

  const educationPolicy = {
    Version: "2027-05-31",
    Id: "DJSCE-BTech-IT-EducationPolicy",
    Statement: [
      {
        Sid: "GrantCoreEngineeringCompetency",
        Effect: "Allow",
        Principal: person.name,
        Action: [
          "engineering:DesignSystems",
          "engineering:DebugProduction",
          "cloud:ProvisionInfrastructure",
          "fullstack:ShipFeatures",
        ],
        Resource: `arn:edu:djsce:in:btech-it/class-of-${education.graduation}`,
        Condition: {
          NumericGreaterThanEquals: { "academic:cgpa": education.gpa.replace("+ CGPA", "") },
        },
      },
      {
        Sid: "DenyGraduationBeforeCompletion",
        Effect: "Deny",
        Action: "academic:ConferDegree",
        Resource: "*",
        Condition: {
          DateLessThan: { "aws:CurrentTime": `${education.graduation}-05-31T00:00:00Z` },
        },
      },
    ],
  };

  return (
    <div className="mx-auto flex max-w-6xl flex-col gap-6">
      <PageHeader
        eyebrow={`${isAws ? "IAM" : "IAM & Admin"} / Users / harsh-goilkar`}
        title="harsh-goilkar"
        description="Identity summary and attached permissions for this user. Least-privilege was considered and immediately overruled by ambition."
        right={<Badge tone="success"><ShieldCheck className="h-3 w-3" /> Active</Badge>}
      />

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <Panel>
          <PanelHeader title="User Details" />
          <dl className="space-y-3 text-sm">
            <Row label="User ARN" value={theme.userArn} mono />
            <Row label="Console access" value="Enabled" />
            <Row label="MFA" value="Enabled (two-factor grit)" />
            <Row label="Created" value="August 2023 -- matriculation event" />
            <Row label="Institution" value={education.institution} />
            <Row label="Degree" value={education.degree} />
            <Row label="Expected graduation" value={education.graduation} />
            <Row label="Academic standing" value={education.gpa} />
          </dl>
        </Panel>

        <Panel>
          <PanelHeader title="Group Memberships" icon={<Users className="h-4 w-4" />} />
          <div className="flex flex-wrap gap-2">
            <Chip>DJSCE-IT-Batch-2027</Chip>
            <Chip>Cloud-Practitioners</Chip>
            <Chip>Full-Stack-Contributors</Chip>
            <Chip>DJS-CSI-Productions</Chip>
            <Chip>DJS-Anveshan-Creatives</Chip>
          </div>
          <p className="mt-4 text-xs leading-relaxed" style={{ color: "var(--text-muted)" }}>
            Group membership grants inherited permissions across academic and
            extracurricular resources. See Monitoring for activity generated by
            these groups.
          </p>
        </Panel>

        <Panel>
          <PanelHeader title="Access Keys" icon={<KeyRound className="h-4 w-4" />} />
          <div className="space-y-2 text-sm">
            <div className="flex items-center justify-between rounded-md border px-3 py-2" style={{ borderColor: "var(--border-subtle)" }}>
              <span className="font-mono text-[12px]" style={{ color: "var(--text-secondary)" }}>
                CURIOSITY_ACCESS_KEY
              </span>
              <Badge tone="success">Active</Badge>
            </div>
            <div className="flex items-center justify-between rounded-md border px-3 py-2" style={{ borderColor: "var(--border-subtle)" }}>
              <span className="font-mono text-[12px]" style={{ color: "var(--text-secondary)" }}>
                IMPOSTER_SYNDROME_KEY
              </span>
              <Badge tone="warning">Rotate recommended</Badge>
            </div>
          </div>
        </Panel>
      </div>

      <Panel>
        <PanelHeader
          title="Attached Policy -- EducationCredentialsPolicy"
          subtitle="JSON policy document. Statement evaluated and confirmed valid by DJSCE Examinations Cell."
        />
        <PolicyDocument document={educationPolicy} />
      </Panel>
    </div>
  );
}

function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="text-xs" style={{ color: "var(--text-muted)" }}>
        {label}
      </dt>
      <dd className={mono ? "break-all font-mono text-[12px]" : ""} style={{ color: "var(--text-primary)" }}>
        {value}
      </dd>
    </div>
  );
}
